---
- name: Crear Usuario
  hosts: all
  become: true

  tasks:
    - name: Crear un nuevo usuario
      ansible.builtin.user:
        name: "{{ user_name }}"
        state: present
        create_home: true
