---
- name: Verificar Usuario
  hosts: all
  become: true

  tasks:
    - name: Verificar existencia de Usuario
      ansible.builtin.user:
        name: "{{ user_name }}"
      check_mode: true
      register: user_check   
      
    - name: Reportar status de usuario
      ansible.builtin.debug:
        msg: "El Usuario {{ user_name }} existe."
      when: user_check.state | d('') == 'present'
