---
- name: Verificar Usuario
  hosts: all
  become: true

  tasks:
    - name: Verificar existencia de Usuario
      ansible.builtin.command:
        cmd: "id {{ user_name }}"
      register: user_check

    - name: Reportar status de usuario
      ansible.builtin.debug:
        msg: "El Usuario {{ user_name }} existe."
      when: user_check.rc == 0
